tickers = {
    "SP500": ("^GSPC", "rsi"),
    "Nasdaq": ("^IXIC", "rsi"),
    "EURO600": ("EXSA.DE", "rsi"),
    "Japan": ("1306.T", "rsi"),
    "CSI300": ("3188.HK", "rsi"),
    "HangSeng": ("^HSI", "rsi"),
    "CQQQ": ("CQQQ", "rsi"),
    "Vietnam": ("VNM", "rsi"),
    "Thailand": ("^SET.BK", "rsi"),
    "CyberSecETF": ("CIBR", "rsi"),
    "Gold": ("GC=F", "price"),
    "BRENT-Oil": ("BZ=F", "price"),
    "THB/USD": ("THB=X", "price"),
}